version: "3.8"

services:
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"


  gremlin:
    image: tinkerpop/gremlin-server:latest
    ports:
      - "8182:8182"
