version: "3.8"

services:
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      Gremlin__UseGremlinServer: "true"
      Gremlin__Host: "ws://gremlin:8182"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:80"

  app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    volumes:
      - $PWD/react-app:/app'
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  gremlin:
    image: tinkerpop/gremlin-server:latest
    container_name: gremlin
    ports:
      - "8182:8182"
